### ISSUE TITLE
Problem with PKGBUILD

### ISSUE THREAD

**Issue by LordVladneutral** [gentoo-root/jacklistener#7] opened 2016-11-19 18:00 UTC
In Archlinux, before installing, it says there is a conflict with /usr/sbin because it already exists... which is normal.

**Comment by gentoo-root** [comment] 2016-11-20 09:46
Are you using this PKGBUILD? https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jacklistener-git
I'm no longer a maintainer of this PKGBUILD, so you should contact the author of the PKGBUILD about PKGBUILD bugs.

I have no Archlinux to check, but it seems to me that the problem is that /usr/sbin is a symlink to /usr/bin in Arch, and `make DESTDIR="$pkgdir" install` installs jacklistener-runscript to `"$pkgdir/usr/sbin"`, thus creating a *directory* /usr/sbin that conflicts then with the *symlink* /usr/sbin in the filesystem. The PKGBUILD author tries to fix that by installing jacklistener-runscript manually to /usr/bin: `install -D init.d/jacklistener-runscript $pkgdir/usr/bin/jacklistenerd-runscript`, but the proper fix would be passing `--sbindir=/usr/bin` to the configure script.

I've found several other issues though (invalid permissions on jacklistener-runscript, wrong path of jacklistenerd in jacklistener-runscript), I'm going to fix them, so that all these workarounds in the PKGBUILD would be unnecessary, but the /usr/sbin issue should be simply fixed by passing `--sbindir=/usr/bin` to the configure script in the PKGBUILD.

**Comment by gentoo-root** [comment] 2016-11-20 10:04
79b6bcf1cbad78e1741218144b6370c8db81b2be fixes the issue with paths, and I suggest the following fix to the PKGBUILD (not tested!):
```patch
--- PKGBUILD.orig	2016-11-20 11:57:07.279593901 +0200
+++ PKGBUILD	2016-11-20 11:57:49.376364887 +0200
@@ -1,7 +1,7 @@
 # Maintainer: M0Rf30
 
 pkgname=jacklistener-git
-pkgver=46.6779b2e
+pkgver=47.79b6bcf
 pkgrel=1
 pkgdesc="Jack Listener Daemon (jack-sensing)"
 arch=('i686' 'x86_64')
@@ -24,15 +24,13 @@
   autoheader
   automake --add-missing
   autoconf
-  ./configure --prefix=/usr --sysconfdir=/etc --enable-systemd --enable-arch
+  ./configure --prefix=/usr --sysconfdir=/etc --sbindir=/usr/bin --enable-systemd
   make
 }
 
 package() {
    cd jacklistener
    make DESTDIR="$pkgdir" install
-   install -D init.d/jacklistener-runscript $pkgdir/usr/bin/jacklistenerd-runscript
-   install -D jacklistenerd $pkgdir/usr/lib/jacklistener/jacklistenerd
 }
 
 pkgver() {
```
You should contact the maintainer of the PKGBUILD about fixing this issue. If any upstream bugs still remain, feel free to open a bug here.

**Closed by gentoo-root** 2016-11-20 10:04 UTC
